name: Build Kernel

on:
  push:
    paths:
      - ".github/workflows/main.yml"
  workflow_dispatch:

defaults:
  run:
   shell: bash

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup package
        run: |
          find . -type f -exec chmod 777 {} +
          ./package
          
      - name: Clone Crosstool
        run: |
          git clone --depth=1 -b karashi https://github.com/techyminati/AnyKernel3 anykernel
          git clone --depth=1 https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 -b master-kernel-build-2021 $HOME/toolchain/aarch64
          git clone --depth=1 https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9 -b master-kernel-build-2021 $HOME/toolchain/arm
     
      - name: KernelSU + Clean
        run: |
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s v0.9.5

      - name: Clean
        run: |
          make clean; make mrproper

      - name: Build
        run: |
          ./build

